### ISSUE TITLE
[REFACTOR] BannerToXXXX

### ISSUE THREAD

**Issue by Clm-Roig** [ugopulito/OC_Projet5#1]
Dans `bannerToLeft` et `bannerToRight`, tu as quasiment les mêmes 4 dernières lignes :

https://github.com/ugopulito/OC_Projet5/blob/803e38986231598836e7bf6ebd1c7e05cd096bcc/assets/script.js#L67-L70

https://github.com/ugopulito/OC_Projet5/blob/803e38986231598836e7bf6ebd1c7e05cd096bcc/assets/script.js#L79-L82

Je te propose de refactoriser (= regrouper) ce doublon dans une seule et même fonction du nom de ton choix (`updateBanner` ?). Celle-ci sera appelée dans `bannerToLeft` et `bannerToRight`, à la place des 4 dernières lignes.

**Comment by ugopulito** [comment]
Effectivement c'était redondant, j'ai ajouté une fonction updateBanner que j'ai ensuite appelée dans mes deux fonctions bannerToRight et bannerToLeft
