### ISSUE TITLE
[REFACTOR] Code Layout

### ISSUE THREAD

**Issue by Clm-Roig** [ugopulito/OC_Projet5#2]
Dans script.js, tu as : 
1. les données de tes slides
2. diverses fonctions appelées par les eventListener 
3. un script qui initialise le tout. 

... le tout un peu mélangé ! C'est-à-dire que si je me réfère aux chiffres ci-dessus (1, 2 et 3), ta structure est la suivante : 
```sh
1 # <-- données
3 # <-- script
2 # createBullet
2 # selectedDot
3 # <-- script
2 # moveDot
2 # moveDot
3 # <-- script
2 # bannerTo
2 # bannerTo
3 # <-- script
```

Généralement, on met toutes les définitions de variables et de fonctions en premier, en haut du fichier. Puis viens l'initialisation et l'exécution du script à proprement parler. Ce qui donnerait : 

```sh
1 
# === Fin déclaration des données
2
2
2
2
2
2
# === Fin déclaration des fonctions
3

**Comment by ugopulito** [comment]
Oui je me demandais s'il était d'usage de déclarer les fonctions là où on en avait besoin ou de tout déclarer au début. Mais effectivement comme ça on ne risque pas de l'utiliser avant de l'avoir déclarée.

**Comment by Clm-Roig** [comment]
À terme, tu feras des fichiers séparés même, ce sera encore plus clair. Mais pour ce petit projet, c'est suffisant de juste les mettre au début.
