### ISSUE TITLE
[STYLE] Quelques suggestions

### ISSUE THREAD

**Issue by Clm-Roig** [ugopulito/OC_Projet5#3]
La petite cerise sur le gâteau : tu pourrais rajouter un effet de survol (clic aussi ?) sur les chevrons droit et gauche. Un truc tout simple, ne te prend pas la tête. L'intérêt pour l'utilisateur c'est d'avoir un feedback comme quoi il vient d'accomplir l'action.

**Comment by ugopulito** [comment]
J'ai fait ça en CSS en ajoutant les pseudo-classes :hover et :active à .arrow. Est-ce que c'est bien comme ça que tu voulais que je fasse ou tu souhaitais que je trouve une solution en js  ?

**Comment by Clm-Roig** [comment]
En CSS uniquement, c'est bon ! :)
